services:
  postgresql:
    image: postgres:15
    env_file: ./env/postgresql.env
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10

  app-1: &app
    build:
      context: .
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy

  app-2:
    <<: *app

  nginx:
    image: nginx:stable-alpine
    ports:
        - "80:80"
    volumes:
        - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - app-1
      - app-2

  redis:
    image: redis:7.2.4
    restart: unless-stopped

volumes:
  postgresql-data:
