spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/codechella
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: redis
    port: 6379

app:
  security:
    jwt:
      secret: 12345678
