spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  security:
    jwt:
      secret: ${APP_JWT_SECRET}
